name: Gitleaks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install and run Gitleaks
        run: |
          LATEST_TAG=$(curl -s "https://api.github.com/repos/gitleaks/gitleaks/releases/latest" | grep '"tag_name":' | sed -E 's/.*"v([^"]+)".*/\1/')
          curl -sSfL "https://github.com/gitleaks/gitleaks/releases/download/v${LATEST_TAG}/gitleaks_${LATEST_TAG}_linux_x64.tar.gz" | sudo tar -xz -C /usr/local/bin gitleaks
          gitleaks detect --verbose --redact
